title: Popup Arcade
description: "Connecting people through public game experiences."
permalink: /posts/:title
baseurl: ''
exclude: [node_modules, tmp, bin, assets/deps.css]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
